name: Test

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        emacs-version:
          - 27.2
          - 28.2
          - 29.4
          - 30.1
          - snapshot
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        exclude:
          - os: macos-latest
            emacs-version: 27.2
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Emacs
        uses: jcs090218/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}
      - name: Setup Eask
        uses: emacs-eask/setup-eask@master
        with:
          version: snapshot
      - name: Run ERT tests
        run: eask test ert-runner
      - name: Lint with checkdoc
        if: always()
        run: eask lint checkdoc
      - name: Lint with package-lint
        if: always()
        run: eask lint package
